### ISSUE TITLE
Finalize Requirements

### ISSUE THREAD

**Issue by damlaalkan** [SWE-574-GROUP-1/SWE574-GROUP-1#31]
The requirements for Posts, Spaces, Badges, Recommendations and Tags had finalized and documented in Wiki Page.

https://github.com/SWE-574-GROUP-1/SWE574-GROUP-1/wiki/%F0%9F%94%8D-2.-Mockup-&-Requirements-&-User-Stories

**Comment by uskudarli** [comment]
Some quick feedback.

The coverage is pretty good. Alas, there are some issues that I will summarize below.

The mockups:

1.  are pretty decent.
2. Should give ID and title to each mockup
3. The annotation could be described a bit better to illustrate the nature of how annotations would be made
4. The semantic tags are not clear.

The recommendations:

1. You have forgotten to give unique ID s for each recommendation. You still have bullet points.
2. You have specified using to conventions (should format as well as user stories a la agile). This leads to overlapping requirements. Pick one and specify them consistently.
3. The semantic tags are not clearly articulated. This: `user shall be able to crate two different type of tags a informative and Wikidata` is not specific enough and I can already see that it is not correct.
4. Spaces: `The user shall be able to create a space in the system.`  is not specific enough.  You have some requirements that seem to be related. You can make them sub-level requirements so that all requirements related to the space creation are clearly and unambiguously defined.

(keep (4) in mind to revise similar requirements. ) As an example:  it should be clear what information is needed to create spaces.

Please revise and inform me when it is done. @damlaalkan  you (or your team) can re-assign to related parties as you see filt.

**Comment by Fluentum** [comment]
Requirements finalized and agreed with Suzan Hoca.
